# Generated by Django 3.2.7 on 2021-12-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelRelationship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('standard', models.CharField(choices=[('primary', (('KG', 'kindergarten'), ('UKG', 'upperkindergarten'))), ('secondary', (('One', 'one'), ('Two', 'two'), ('Three', 'three'), ('Four', 'four'), ('Five', 'five'), ('Six', 'six'), ('Seven', 'seven'), ('Eight', 'eight'), ('Nine', 'nine'), ('Ten', 'ten'))), ('higher secondary', (('Eleven', 'eleven'), ('Twelve', 'twelve')))], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
