# Generated by Django 3.2.7 on 2022-02-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelRelationship', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='standard',
        ),
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('S', 'Science'), ('C', 'Commerce'), ('H', 'Humainity')], default='Science', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('FRESHMAN', 'Freshman'), ('SOPHOMORE', 'Sophpmore'), ('GRADUATE', 'Graduate'), ('SENIOR', 'Senior'), ('JUNIOR', 'Junior')], default='Freshman', max_length=9),
        ),
    ]
