# Generated by Django 3.2.7 on 2022-02-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelRelationship', '0003_auto_20220204_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyStudent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ModelRelationship.student',),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('S', 'Science'), ('C', 'Commerce'), ('H', 'Humainity')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('FRESHMAN', 'Freshman'), ('SOPHOMORE', 'Sophpmore'), ('GRADUATE', 'Graduate'), ('SENIOR', 'Senior'), ('JUNIOR', 'Junior')], max_length=9),
        ),
    ]
