# Generated by Django 3.2.7 on 2022-02-04 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelRelationship', '0004_auto_20220204_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mystudent',
            options={'ordering': ['first_name']},
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ModelRelationship.company')),
                ('established', models.DateField()),
            ],
            bases=('ModelRelationship.company',),
        ),
    ]
