# Generated by Django 3.2.6 on 2022-02-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelRelationship', '0005_auto_20220204_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='established',
            field=models.DateField(blank=True),
        ),
    ]
