# Generated by Django 3.2.6 on 2022-02-22 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelRelationship', '0006_alter_companyprofile_established'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_entries', to='ModelRelationship.blog'),
        ),
    ]
