# Generated by Django 4.1.1 on 2022-09-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelRelationship', '0009_auto_20220222_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
    ]
