# Generated by Django 3.2.7 on 2022-02-01 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'Username already taken.'}, max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', code='invalid', message='Only alphabet are allowed.')])),
                ('last_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', code='invalid', message='Only alphabet are allowed.')])),
                ('date_of_birth', models.DateField()),
                ('email', models.CharField(max_length=100, validators=[django.core.validators.EmailValidator(code='invalid', message='Please enter a valid email address')])),
                ('comments', models.TextField(max_length=1000)),
            ],
        ),
    ]
